name: Build wasm packages
description: |
  Build a list of R packages for WebAssembly, create an R library, and build a
  CRAN-like repository containing the R package binaries.
inputs:
  packages:
    description: A file containing a list of R package references.
    default: packages
    required: true
  upload-image:
    description: |
      Should the R package library filesystem image be uploaded as an artifact?
    default: true
    required: true
  upload-repo:
    description: |
      Should the R package repository be uploaded as an artifact?
    default: true
    required: true
runs:
  using: "composite"
  steps:
    - name: Install the pak and rwasm R packages
      run: |
        /usr/bin/R --silent -e 'install.packages("pak")'
        /usr/bin/R --silent -e 'pak::pak("r-wasm/webr-repo@pkg")'
      shell: bash
    - name: Build Wasm R packages
      run: |
        /usr/bin/R --silent -e 'rwasm::add_list("${{ inputs.packages }}")'
        /usr/bin/R --silent -e 'rwasm::make_vfs_library()'
      shell: bash
    - name: Upload R package repository
      if: ${{ inputs.upload-repo == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: wasm-repo
        path: repo
    - name: Upload R package library filesystem image
      if: ${{ inputs.upload-image == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: wasm-image
        path: |
          vfs/library.data
          vfs/library.js.metadata
