# action.yml
name: 'Build wasm packages action'
description: 'Build wasm packages using r-wasm/rwasm'
inputs:
  packages:
    description: A string of R package references.
    required: true
  strip:
    description: |
      A set of [directories to remove](https://r-wasm.github.io/rwasm/reference/make_library.html#details) when building the WebAssembly R package library image, or `NULL` to remove nothign (the default). To achieve a smaller bundle size, it is recommended to set `strip` to `"demo, doc, examples, help, html, include, tests, vignette"`.
    default: "NULL"
    required: false
  image-path:
    description: Directory where the R package library filesystem image files should be saved.
    default: "."
    required: false
  repo-path:
    description: Directory where the R package repository should be saved.
    default: "_site"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    # - Rscript
    - /code.R
    - ${{ inputs.image-path }}
    - ${{ inputs.repo-path }}
    - ${{ inputs.packages }}
    - ${{ inputs.strip }}
