# action.yml
name: 'Build wasm packages action'
description: 'Build wasm packages using r-wasm/rwasm'
inputs:
  packages:
    description: A set of R package values
    required: true
  strip:
    description: |
      An R expression evaluating to a character vector of directories to strip
      when building the R package library image.
    default: "NULL"
    required: false
outputs:
  vfs_dir:
    description: 'Directory of the R package library filesystem image'
  repo_dir:
    description: 'Directory of the R package repository'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # env:
  #   GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  args:
    # - Rscript
    - /code.R
    - ${{ inputs.packages }}
    - ${{ inputs.strip }}
