# action.yml
name: 'Build wasm packages action'
description: 'Build wasm packages using r-wasm/rwasm'
inputs:
  packages:
    description: A set of R package values
    required: true
  strip:
    description: |
      An R expression evaluating to a character vector of directories to strip
      when building the R package library image.
    default: "NULL"
    required: false
  image-path:
    description: Directory of where to save the R package library filesystem image
    default: ""
    required: false
  repo-path:
    description: Directory of where to save the R package repository
    default: ""
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    # - Rscript
    - /code.R
    - ${{ inputs.image-path }}
    - ${{ inputs.repo-path }}
    - ${{ inputs.packages }}
    - ${{ inputs.strip }}
