# Workflow derived from https://github.com/r-wasm/actions/tree/v1/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: Build wasm R package repository

jobs:
  build:
    uses: r-wasm/actions/.github/workflows/build.yml@v1
    with:
      strip: c("demo", "doc", "examples", "help", "html", "include", "tests", "vignette")
  deploy:
    name: Deploy to GitHub pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Download wasm artifacts
        uses: r-wasm/actions/download-wasm-artifacts@v1
        with:
          repo-path: _site
          image-path: _site
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
