# Workflow derived from https://github.com/r-wasm/actions/tree/v1/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  release:
    # Must republish release to update assets
    types: [ published ]

name: Build and deploy wasm R package image

jobs:
  image-release:
    uses: r-wasm/actions/.github/workflows/image-release.yml@v1
    permissions:
      # For publishing artifact to release
      contents: write
      # To download GitHub Package within action
      repository-projects: read
    with:
      strip: c("demo", "doc", "examples", "help", "html", "include", "tests", "vignette")
