name: Build wasm package image
description: |
  Build an image of a set of R packages for WebAssembly.
inputs:
  packages:
    description: A set of R package values.
    required: true
  strip:
    description: |
      An R expression evaluating to a character vector of directories to strip
      when building the R package library image.
    default: "NULL"
    required: false
  path:
    description: |
      The path to the directory containing the R package library filesystem
      image. By default, it will save to `./_site`.
    default: _site
    required: false
runs:
  using: "composite"
  steps:
    - name: Build wasm package image
      uses: ./.github/actions/build-rwasm
      with:
        packages: ${{ inputs.packages }}
        image-path: ${{ inputs.path }}
        strip: ${{ inputs.strip }}
