on:
  release:
    types: [published]

name: r-wasm/actions - image

jobs:
  image:
    uses: ./.github/workflows/release-filesystem-image.yml
    with:
      packages: cli
    permissions:
      contents: write
      repository-projects: read
