on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: r-wasm actions

jobs:
  build-workflow:
    # Uses `build-wasm-packages@v1` internally
    uses: ./.github/workflows/build.yml
    with:
      packages: .github/_testing/packages
  build:
    name: Build wasm artifacts
    runs-on: ubuntu-latest
    container: ghcr.io/r-wasm/webr:main
    steps:
      - uses: actions/checkout@v3
      - name: Build wasm packages
        uses: ./build-wasm-packages
        with:
          packages: .github/_testing/packages
  download:
    name: Download wasm artifacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download wasm artifacts
        uses: ./download-wasm-artifacts
        with:
          repo-path: _site
          image-path: _site
