on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: r-wasm/actions - repo

jobs:
  reuse-workflow-repo:
    uses: ./.github/workflows/build-and-deploy-repo.yml
    with:
      packages: cli
    permissions:
      repository-projects: read
      pages: write
      id-token: write

  # reuse-workflow-image:
  #   uses: ./.github/workflows/release-image.yml
  #   with:
  #     packages: cli
  #   permissions:
  #     contents: write
  #     repository-projects: read

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./build-image
        with:
          packages: cli
          image-path: _image
      - name: Verify repo exist
        shell: Rscript {0}
        run: |
          print(dir("_image", recursive = TRUE))
          stopifnot(file.exists("_image/library.data"))
          stopifnot(file.exists("_image/library.js.metadata"))
  build-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build wasm packages
        uses: ./build-repo
        with:
          packages: |
            cli
          repo-path: _repo
      - name: Verify repo exist
        shell: Rscript {0}
        run: |
          print(dir("_repo", recursive = TRUE))
          stopifnot(dir.exists("_repo/src"))
          stopifnot(dir.exists("_repo/bin"))
