on:
  push:

name: Build and deploy repository

jobs:
  # Build and upload the wasm packages
  repository:
    # Should match the name of `./build-wasm-packages` action name
    name: "Build and deploy repository"
    runs-on: ubuntu-latest
    # Only run latest version of website
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    permissions:
      # write-all
      pages: write
      id-token: write
      repository-projects: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3

      # Needed to be able to adjust files after running Dockerfile
      # Related: https://github.com/actions/runner/issues/434
      - name: Use Docker in rootless mode.
        uses: ScribeMD/rootless-docker@0.2.2

      - name: Build wasm packages
        uses: ./.github/actions/build-rwasm
        id: rwasm
        env:
          # Would like to move this into the action itself
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          packages: cli

      - name: Show dir contents
        run: ls -Rlth .

      - name: Move files from vfs to _site
        run: |
          mkdir -p _site
          mv ${{ steps.rwasm.outputs.vfs-dir }}/library.data _site/library.data
          mv ${{ steps.rwasm.outputs.vfs-dir }}/library.js.metadata _site/library.js.metadata
          mv ${{ steps.rwasm.outputs.repo-dir }}/* _site/

      - name: Show dir contents
        run: ls -Rlth .

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
