on:
  # Allow users to run this workflow via reusable workflow
  # Avoids boiler plate of setting the container and running the single steps
  # Ex:
  # jobs:
  #   build:
  #     uses: r-wasm/actions/.github/workflows/build.yml@v1
  workflow_call:
    inputs:
      # New input parameters
      name:
        description: The name of the job
        default: "Build wasm packages"
        type: string
        required: false
      # !! ./build-wasm-packages/action.yml inputs!!
      packages:
        description: A file containing a list of R package references.
        default: packages
        type: string
        required: false
      upload-image:
        description: |
          Should the R package library filesystem image be uploaded as an artifact?
        default: true
        type: boolean
        required: false
      upload-repo:
        description: |
          Should the R package repository be uploaded as an artifact?
          default: true
        type: boolean
        required: false
      strip:
        description: |
          An R expression evaluating to a character vector of directories to strip
          when building the R package library image.
        default: "NULL"
        type: string
        required: false

name: Build wasm R package repository

jobs:
  # Build and upload the wasm packages
  build:
    # Should match the name of `./build-wasm-packages` action name
    name: ${{ inputs.name }}
    # Run the Docker container on the latest ubuntu
    runs-on: ubuntu-latest
    container: ghcr.io/r-wasm/webr:main
    steps:
      - uses: actions/checkout@v3
      - name: Build wasm packages
        uses: r-wasm/actions/build-wasm-packages@v1
        with:
          packages: ${{ inputs.packages }}
          upload-image: ${{ inputs.upload-image }}
          upload-repo: ${{ inputs.upload-repo }}
          strip: ${{ inputs.strip }}
