on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: r-wasm actions

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/r-wasm/webr:main
    steps:
    - uses: actions/checkout@v3
    - name: Build wasm packages
      uses: ./build-wasm-packages
      with:
        packages: .github/workflows/packages
